### ISSUE TITLE
Getting an exception on running

### ISSUE THREAD

**Issue by riyanalewis** [bijukunjummen/sample-webflux-func-cassandra#1]
Hi, 
I am trying to run this and get the exception 
org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'httpHandler' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/HttpHandlerAutoConfiguration$AnnotationConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.server.reactive.HttpHandler]: Factory method 'httpHandler' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webHandler' defined in org.springframework.web.reactive.config.DelegatingWebFluxConfiguration: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in org.springframework.web.reactive.config.DelegatingWebFluxConfiguration: Invocation of init method failed; nested exception is org.springframework.web.util.pattern.PatternParseException: Missing preceeding open capture character before variable name{
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:59)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:44) 

Would you be able to point out if I am missing something, Thanks! :)

**Comment by bijukunjummen** [comment]
Ha, been a while with this project @riyanalewis , let me check and get back to you, likely that I was using a build-snapshot and things changed on the snapshot version. I will pin it to a RC instead and see how that goes

**Comment by bijukunjummen** [comment]
Should be resolved now. Tried with boot 2.0.0.RELEASE
